#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
