#!/usr/bin/env bash
# installs nginx and configures it on a remote server

#!/usr/bin/env bash
# installing nginx and configuring a server

apt install nginx -y
mkdir -p /var/www/
echo "Hello World!" > /var/www/html/index.html
nginx
