#!/usr/bin/env bash
# Installs, configures, and starts the server

apt -y update
apt -y install nginx
mkdir -p /var/www/
echo "Hello World!" > /var/www/html/index.html
string_replace="location /redirect_me {\n		return 301 https://www.facebook.com;\n		}"

sed -i "s#server_name _;#$string_to_replace#" /etc/nginx/sites-available/default
service nginx restart
