#!/usr/bin/env bash

apt -y update
apt -y install nginx
sudo mkdir -p /var/www/
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed  -i "\|root /var/www/html;|a\\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
