#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update -y
sudo apt install haproxy -y
touch /etc/haproxy/haproxy.cfg
chmod +x /etc/haproxy/haproxy.cfg
printf "frontend http\n\tbind *:80\n\tmode http\n\ttimeout client 60s\n\tdefault_backend webservers\nbackend webservers\n\ttimeout connect 20s\n\ttimeout server 100s\n\tmode http\n\tserver 196709-web-01 54.144.156.106 check\n\tserver 196709-web-02 100.26.161.58 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
