#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get -y update
sudo apt-get install haproxy=2.9.\*

echo "ENABLED=1" > /etc/default/haproxy
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 196709-web-01 54.144.156.106:80 check
    server 196709-web-02 100.26.161.58:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
