#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Write a Bash script that configures a server to the above requirements
service nginx start
PORT=80
FIL="/etc/nginx/sites-available/default"
sed "s/listen [0-9]\+/listen $PORT/" "$FIL"
service nginx restart
