#!/usr/bin/env bash
#loop with while    
NUM=1
while [ $NUM -le 20 ]
do
echo $NUM
case $NUM in
4)
echo bad luck from china
;;
9)
echo bad luck from Japan
;;
17)
echo bad luck from Italy
;;
esac
NUM=$((NUM + 1))
done